[phases.setup]
nixPkgs = ["python3", "python3Packages.pip", "postgresql"]

[phases.install]
cmds = ["cd backend && python3 -m pip install -r requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "cd backend && python3 -m gunicorn app.main:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT" 