[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && /opt/venv/bin/alembic upgrade head && /opt/venv/bin/gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE" 