[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && python3 cleanup_db_once.py && gunicorn app.main:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

# Staging environment uses fewer workers to reduce costs