"""Add markup and discount system

Revision ID: 6087350756df
Revises: 
Create Date: 2025-06-27 00:04:57.715298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6087350756df'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_settings', sa.Column('default_material_markup_percent', sa.Numeric(precision=7, scale=4), nullable=True))
    op.add_column('company_settings', sa.Column('default_labor_markup_percent', sa.Numeric(precision=7, scale=4), nullable=True))
    op.add_column('projects', sa.Column('material_markup_type', sa.String(length=10), nullable=True))
    op.add_column('projects', sa.Column('material_markup_percent', sa.Numeric(precision=7, scale=4), nullable=True))
    op.add_column('projects', sa.Column('material_markup_flat', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('projects', sa.Column('labor_markup_type', sa.String(length=10), nullable=True))
    op.add_column('projects', sa.Column('labor_markup_percent', sa.Numeric(precision=7, scale=4), nullable=True))
    op.add_column('projects', sa.Column('labor_markup_flat', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('projects', sa.Column('material_discount_type', sa.String(length=10), nullable=True))
    op.add_column('projects', sa.Column('material_discount_percent', sa.Numeric(precision=7, scale=4), nullable=True))
    op.add_column('projects', sa.Column('material_discount_flat', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('projects', sa.Column('labor_discount_type', sa.String(length=10), nullable=True))
    op.add_column('projects', sa.Column('labor_discount_percent', sa.Numeric(precision=7, scale=4), nullable=True))
    op.add_column('projects', sa.Column('labor_discount_flat', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('projects', sa.Column('project_discount_type', sa.String(length=10), nullable=True))
    op.add_column('projects', sa.Column('project_discount_percent', sa.Numeric(precision=7, scale=4), nullable=True))
    op.add_column('projects', sa.Column('project_discount_flat', sa.Numeric(precision=10, scale=2), nullable=True))
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_title'), 'projects', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_title'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_column('projects', 'project_discount_flat')
    op.drop_column('projects', 'project_discount_percent')
    op.drop_column('projects', 'project_discount_type')
    op.drop_column('projects', 'labor_discount_flat')
    op.drop_column('projects', 'labor_discount_percent')
    op.drop_column('projects', 'labor_discount_type')
    op.drop_column('projects', 'material_discount_flat')
    op.drop_column('projects', 'material_discount_percent')
    op.drop_column('projects', 'material_discount_type')
    op.drop_column('projects', 'labor_markup_flat')
    op.drop_column('projects', 'labor_markup_percent')
    op.drop_column('projects', 'labor_markup_type')
    op.drop_column('projects', 'material_markup_flat')
    op.drop_column('projects', 'material_markup_percent')
    op.drop_column('projects', 'material_markup_type')
    op.drop_column('company_settings', 'default_labor_markup_percent')
    op.drop_column('company_settings', 'default_material_markup_percent')
    # ### end Alembic commands ###
